- .devops/code-review-pipelines.yml
- CODEOWNERS
- GetCertificate/__tests__/handler.test.ts
- GetCertificate/function.json
- GetCertificate/handler.ts
- GetCertificate/index.ts
- openapi/__tests__/models.test.ts
- openapi/dgc.yaml
- openapi/index.yaml
- openapi/index.yaml.template
- package.json
Skeleton of the _getCertificate_ function
Bootstrap of eucovidcert project
> [#IP-198] added getCertificate function

- SubmitMessageForUser/function.json
- SubmitMessageForUser/handler.ts
- SubmitMessageForUser/index.ts
Created the new endpoint SubmitMessageForUser with a summy response.
Add api/v1/messages enpoint with SubmitMessageForUser stub
Dummy endpoint to prepare APIM configuration
Local Azure function test
> Add SubmitMessageForUser dummy Endpoint

- env.example
- host.json
Fix host.json configuration for durable function
add durable function config to host.json
eucovidcerts do not deploy
locl test on azure function tools
> fix host.json config for durable function

- GetCertificate/__tests__/handler.test.ts
- GetCertificate/handler.ts
- openapi/__tests__/models.test.ts
- openapi/index.yaml
- openapi/index.yaml.template
- package.json
* split Certificate info in two different fields: `info` and `details`
* add an optional `preferred_languages` to request params to allow Citizens to request Certificate detail in the language they are more comfortable (between those supported by IO)
To better assist Citizens via a UI which is both complete in what tells, and shows as little data as possible in main Certificate screen.
API spec is valid, models are generated correctly, project builds
> Update Certificate model

- .vscode/launch.json
- GetCertificate/function.json
- GetCertificate/index.ts
Fix _getCertificate_ endpoint
Bugfixing
io-mock
> Fix GetCertificate endpoint

- openapi/dgc.yaml
* update `openapi/dgc.yaml`
* 
This is the API specification DGC provided us, we will use to communicate with it.
> Update DGC api spec

- GetCertificate/__tests__/handler.test.ts
- GetCertificate/handler.ts
- openapi/__tests__/models.test.ts
- openapi/index.yaml
- openapi/index.yaml.template
Update openapi spec based on new Certificate handling:
- replace id with uvci
- replace revoked_reason with revoke_info (markdown value)
- add ExpiredCertificate type
> Update openapi spec

- utils/__tests__/dgcClientSelector.test.ts
- utils/config.ts
- utils/dgc.ts
- utils/dgcClientSelector.ts
- utils/httpsAgent.ts
* add CA to https requests
Functions app don't have CA list updated, so we must provide the CA referenced by our client certificates
> Add CA to signed requests

- SubmitMessageForUser/handler.ts
- utils/__tests__/serviceClient.test.ts
- utils/config.ts
- utils/serviceClient.ts
* select api url endpoint from a pool
* turn `FNSERVICES_API_URL` into a list of endpoint 
We will need to up-scale the capacity of downstream service, with this implementation we can spread our outgoing requests evenly between different instances.
> Handle multiple api url

- utils/serviceClient.ts
When `getLimitedProfileByPost` response status code is 404 `SubmitMessageForUser` returns 403
> [#IPV-95] Return 403 if User profile's is not found

- host.json
set log level to `info`
`trace` level is too high for production service
> Update log level

- host.json
> Fix logLevel

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .devops/yarn-lock-upgrade.yml
Update pipelines templates to v15
Healthcheck error
> Update pipelines templates to v15

- host.json
Disable any sampling for Exception;Event;CustomEvent
"maxTelemetryItemsPerSecond": 20 is the default value
> Improve logging

- host.json
reduce maxTelemetryItemsPerSecond = 5
> Reduce logs

- GetCertificate/__tests__/__snapshots__/parser.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_it.test.ts.snap
- GetCertificate/valuesets/labTestManufactorers.ts
Update `labTestManufacturers` valueset to be aligned with [this list](https://covid-19-diagnostics.jrc.ec.europa.eu/devices?manufacturer&text_name&marking&rapid_diag&format&target_type&field-1=HSC%20common%20list%20%28RAT%29&value-1=1&search_method=AND#form_content)
> dataset cleanup based on new values

- GetCertificate/__tests__/__snapshots__/printer_recovery_info_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_info_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_info_de.test.ts.snap
- GetCertificate/printer.ts
use German printer for info template
Bugfix for German language translation
Unit tests, snapshots
> [#IP-311] Bugfix info template translation

- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_recovery_info_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_info_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_info_de.test.ts.snap
- GetCertificate/markdown/eucovidcertDetailsRecoveryDe.ts
- GetCertificate/markdown/eucovidcertDetailsTestDe.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationDe.ts
- GetCertificate/markdown/eucovidcertInfoVaccinationDe.ts
Minor changes due to feedback for German translation
> fix minor translation errors

- GetCertificate/markdown/eucovidcertInfoVaccinationDe.ts
> Fix german translation

- GetCertificate/__tests__/__snapshots__/printer_test_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_it.test.ts.snap
- GetCertificate/__tests__/printer_test_detail_en.test.ts
- GetCertificate/markdown/eucovidcertDetailsTestDe.ts
- GetCertificate/markdown/eucovidcertDetailsTestEn.ts
- GetCertificate/markdown/eucovidcertDetailsTestIt.ts
- GetCertificate/printer.ts
- GetCertificate/valuesets/labTestTypes.ts
- Update vaccination end check
- Add test type discriminant
- Updated snapshots
Fix GP template based on new rule
Unit tests
> [IP-445]  Fix GP template

- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_it.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_it.test.ts.snap
- GetCertificate/markdown/eucovidcertDetailsRecoveryIt.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationDe.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationEn.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationIt.ts
- GetCertificate/markdown/samples/OK_eucovidcert_details_recovery_it.md
- GetCertificate/markdown/samples/OK_eucovidcert_details_vaccination_en.md
- GetCertificate/markdown/samples/OK_eucovidcert_details_vaccination_it.md
- Set vaccine validity to 9 month in case of last dose or boosters
**NOTE: Do not apply before December 15**
> [#IC-137] Reduce vaccine validity description from 12 to 9 months

- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_en.test.ts.snap
- GetCertificate/markdown/eucovidcertDetailsRecoveryEn.ts
- GetCertificate/markdown/eucovidcertDetailsTestEn.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationEn.ts
- GetCertificate/markdown/samples/OK_eucovidcert_details_recovery_en.md
- GetCertificate/markdown/samples/OK_eucovidcert_details_test_en.md
- GetCertificate/markdown/samples/OK_eucovidcert_details_test_it.md
- GetCertificate/markdown/samples/OK_eucovidcert_details_vaccination_en.md
> [#IC-137] fix translations

- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_test_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_de.test.ts.snap
- GetCertificate/markdown/eucovidcertDetailsRecoveryDe.ts
- GetCertificate/markdown/eucovidcertDetailsTestDe.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationDe.ts
> [#IC-137] fix german translation

- GetCertificate/parser.ts
* split `parseQRCode` function in two main phases
To easy test certificates' data. QR content data can be easily dropped in a unit test to se how would it be rendered
> [#IC-173] Refactor Certificate parsing

- GetCertificate/__tests__/handler.test.ts
- GetCertificate/handler.ts
- GetCertificate/markdown/eucovidcertExpiredInfoDe.ts
- GetCertificate/markdown/eucovidcertExpiredInfoEn.ts
- GetCertificate/markdown/eucovidcertExpiredInfoIt.ts
- GetCertificate/printer.ts
* add text for italian, german and english certificate
Provide a static text to he shown to Citizens once a Certificate is not available for any reason. Due DGC does not discriminate different cases (expired, revoked, not-valid-yet), we are unable to provide a meaningful experience to our Citizens. A workaround is to provide a text generic-enough to include any possible scenario.
> [#IC-172] Add expired info text

- GetCertificate/__tests__/handler.test.ts
- GetCertificate/certificate.headerInfo.ts
- GetCertificate/handler.ts
- GetCertificate/headerInfo.ts
- GetCertificate/printer.ts
- openapi/__tests__/models.test.ts
- openapi/index.yaml
- openapi/index.yaml.template
- utils/conversions.ts
Add new attribute `header_info` to `Certificate` types (Valid, Revoked, Expired), containing:
- title
- subtitle
- logo_id
Fill header_info based on preferred language and certificate type
In order to introduce new Exemption certificate type, let BE define. the certificate title 
unit tests, io-mock
> [#IC-204] Add header info to Certificate objects

- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_it.test.ts.snap
- GetCertificate/markdown/eucovidcertDetailsVaccinationDe.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationEn.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationIt.ts
- Reduce certificate validity from 9 to 6 month in [2bd424a](https://github.com/pagopa/io-functions-eucovidcerts/pull/89/commits/2bd424a8a9d141d8655457e687d63007c7853514) and update snapshots in [2797e6f](https://github.com/pagopa/io-functions-eucovidcerts/pull/89/commits/2797e6fda80430be2a50d49aa37bc4823378ddb8)
Unit tests
> Update certificate validity

- GetCertificate/__tests__/__snapshots__/printer_exemption.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_recovery_detail_it.test.ts.snap
- GetCertificate/markdown/eucovidcertDetailsExemptionIt.ts
- GetCertificate/markdown/eucovidcertDetailsRecoveryDe.ts
- GetCertificate/markdown/eucovidcertDetailsRecoveryEn.ts
- GetCertificate/markdown/eucovidcertDetailsRecoveryIt.ts
- Fix small typo found in new exemption markdown in [6408d78](https://github.com/pagopa/io-functions-eucovidcerts/pull/87/commits/6408d78856eea307e4c7131d252d13cb02756d53)
- Fix bold issue in recovery template in [47cd6e6](https://github.com/pagopa/io-functions-eucovidcerts/pull/87/commits/47cd6e6e1b647a262c4801c7d842b72b1eef8be4) and updated snapshots in [cd2cedf](https://github.com/pagopa/io-functions-eucovidcerts/pull/87/commits/cd2cedf91b36d90c232ffcf2b5a1f1eb8b0832d5)
> [#IC-189] Fix typo in exemption markdown

- NotifyNewProfileToDGC/__tests__/handler.test.ts
- NotifyNewProfileToDGC/handler.ts
- openapi/dgc.yaml
- handled 404 response from refresh endpoint in [dfca707](https://github.com/pagopa/io-functions-eucovidcerts/pull/92/commits/dfca707bb230e967448d47bc0d0ced04cbe3ab69)
- test added in [ab18ece](https://github.com/pagopa/io-functions-eucovidcerts/pull/92/commits/ab18ecee27b0672220f9baf1f582c97a7f37554f)
Unit tests
> [#IC-251] handle 404 response from refresh endpoint

- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_de.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_en.test.ts.snap
- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_it.test.ts.snap
- GetCertificate/__tests__/printer_vaccine_detail_de.test.ts
- GetCertificate/__tests__/printer_vaccine_detail_en.test.ts
- GetCertificate/__tests__/printer_vaccine_detail_it.test.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationDe.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationEn.ts
- GetCertificate/markdown/eucovidcertDetailsVaccinationIt.ts
- GetCertificate/printer.ts
- Introduced new check `isBooster` that checks if a vaccination is a booster ( cases: 3/2, 3/3, 2/1) and handled new description for this new case in [7e87a50](https://github.com/pagopa/io-functions-eucovidcerts/pull/91/commits/7e87a502063b828770b77a0712852c7e84b094f8)
- added new tests for vaccination details in case of 3/2, 3/3, 2/1 in [290eca0](https://github.com/pagopa/io-functions-eucovidcerts/pull/91/commits/290eca046019e06b9c86374c20f5a67141365c92)
- updated snapshots in [8d624c2](https://github.com/pagopa/io-functions-eucovidcerts/pull/91/commits/8d624c2f49307ce332367c42e918caaec99c5939). 
Note: old snapshots are not changed
> [IC-250]  Update descriptions in case of booster

- GetCertificate/__tests__/__snapshots__/printer_vaccine_detail_it.test.ts.snap
- GetCertificate/__tests__/printer_vaccine_detail_it.test.ts
- GetCertificate/printer.ts
Fix vaccination details for 4/4 dose
> Fix vaccination details for 4/4 dose

- .vscode/settings.json
- docker/azurite/Dockerfile
- docker/cosmosdb/Dockerfile
- docker/functions/Dockerfile
- extensions.csproj
- host.json
- package.json
- proxies.json
- yarn.lock
See commit list
v3 is going out of LTS
> [#IOPAE] Upgrade to Aure Functions engine v4
